{{- if and .Values.govway.enabled (ne .Values.govway.database.type "hsql") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oas-checker.fullname" . }}-govway
  labels:
    {{- include "oas-checker.govway.labels" . | nindent 4 }}
type: Opaque
stringData:
  GOVWAY_DB_PASSWORD: {{ .Values.govway.database.password | quote }}
{{- end }}
