{{- if and .Values.govway.enabled .Values.govway.keys.publicKey .Values.govway.keys.privateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oas-checker.fullname" . }}-govway-keys
  labels:
    {{- include "oas-checker.govway.labels" . | nindent 4 }}
type: Opaque
stringData:
  public_key.pem: |
    {{- .Values.govway.keys.publicKey | nindent 4 }}
  private_key.pem: |
    {{- .Values.govway.keys.privateKey | nindent 4 }}
{{- end }}
